---
title: "Lesson 5 HW"
author: "Joshua Susanto"
date: "4/20/2021"
output: html_document
---

# 1

## A(1)
```{r}
options(width = 121)
library(readr)

a <- read_delim("https://www.gbcnv.edu/bookstore/2021-Fall.txt",
                delim = "\t",col_types =  cols(X1 = col_logical(),
  X2 = col_character(),
  X3 = col_character(),
  X4 = col_character(),
  X5 = col_logical(),
  X6 = col_character(),
  X7 = col_character(),
  X8 = col_character(),
  X9 = col_logical(),
  X10 = col_double(),
  X11 = col_double(),
  X12 = col_logical(),
  X13 = col_logical()),
                col_names = FALSE)
                
 a<- a[,c(2:4,6:8,10:11)]     
```

## A(2)
```{r}
dim(a)
```

## A(3)
```{r}
one_A <- a
head(one_A)
```

## A(4)
```{r}
colnames(one_A) <- c("dept","number","course","room","building","instructor","enroll","cap")
```

## B(1)
```{r}
b <- read.delim("https://www.gbcnv.edu/bookstore/2021-Fall.txt", 
                col.names = c("V1","V2","V3","V4","V5","V6","V7","V8","V9","V10","V11","V11","V12"),header=FALSE)
b <- b[,c(2:4,6:8,10:11)] 
```

## B(2)
```{r}
dim(b)
```

## B(3)
```{r}
one_B <- b
head(one_B)
```

## B(4)
```{r}
colnames(one_B) <- c("dept","number","course","room","building","instructor","enroll","cap")
```

# 2

## A(1)
```{r}
load("raceprofiling.rdata")
raceprofileB <- raceprofiling[raceprofiling$resident == 1, c(10,8,9,7)]
```

## A(2)
```{r}
write_csv(raceprofileB, file="raceprofileB.csv")
```

## A(3)
```{r}
c <- read_csv("raceprofileB.csv",cols(
  citation = col_character(),
  male = col_character(),
  race = col_character(),
  age = col_character()), col_names = TRUE)
head(c)
```

## B(1)
```{r}
load("raceprofiling.rdata")
raceprofileD <- raceprofiling[raceprofiling$resident == 1, c(10,8,9,7)]
```

## B(2)
```{r}
write.csv(raceprofileD, file="raceprofileD.csv")
```

## B(3)
```{r}
d <- read.csv("raceprofileD.csv")
head(d)
```

